[phases.setup]
nixPkgs = ["jdk17", "ffmpeg", "python3"]

[phases.build]
cmds = [
    "pip install yt-dlp --target=/usr/local/lib/yt-dlp",
    "ln -sf /usr/local/lib/yt-dlp/bin/yt-dlp /usr/local/bin/yt-dlp",
    "./gradlew --no-build-cache clean buildFatJar"
]